[package]
name = "hello-rust"
version = "0.1.0"
authors = ["tims <tsteeman@jibes.nl>, greg <gr3g.mk@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
select = "*"
scraper = "*"
text_io = "*"
serde_json = "1.0.39"
serde_derive = "1.0.93"
rocket = "0.4.1"
